export const ERROR = 'FOOD/ERROR'
export const LOADING = 'FOOD/LOADING'
export const CLEAR_MESSAGE = 'FOOD/CLEAR_MESSAGE'

export const CREATE = 'FOOD/CREATE'
export const READ = 'FOOD/READ'
export const READ_ALL = 'FOOD/READ_ALL'
export const UPDATE = 'FOOD/UPDATE'
export const DELETE = 'FOOD/DELETE'
export const SOFT_UPDATE = 'FOOD/SOFT_UPDATE'
