export const ERROR = 'AUTH/ERROR'
export const LOADING = 'AUTH/LOADING'
export const READ_USER = 'AUTH/READ_USER'
export const SIGN_IN = 'AUTH/SIGN_IN'
export const CLEAR_MESSAGE = 'AUTH/CLEAR_MESSAGE'
