export const ERROR = 'REFERENCE/ERROR'
export const LOADING = 'REFERENCE/LOADING'
export const CLEAR_MESSAGE = 'REFERENCE/CLEAR_MESSAGE'

export const CREATE = 'REFERENCE/CREATE'
export const READ = 'REFERENCE/READ'
export const READ_ALL = 'REFERENCE/READ_ALL'
export const UPDATE = 'REFERENCE/UPDATE'
export const DELETE = 'REFERENCE/DELETE'

export const FILTER = 'REFERENCE/FILTER'
export const CLEAR_FILTER = 'REFERENCE/CLEAR_FILTER'
